# Air configuration for cisco-wnc-exporter CLI development
# Documentation: https://github.com/air-verse/air

tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/cisco-wnc-exporter ./cmd/main.go"
  full_bin = 'tmp/cisco-wnc-exporter \
                  --wnc.tls-skip-verify \
                  --web.listen-port 3000 \
                  --collector.ap.general \
                  --collector.ap.radio \
                  --collector.ap.traffic \
                  --collector.ap.errors \
                  --collector.ap.info \
                  --collector.ap.info-labels "name,ip,band,model,serial,sw_version,eth_mac" \
                  --collector.client.general \
                  --collector.client.radio \
                  --collector.client.traffic \
                  --collector.client.errors \
                  --collector.client.info \
                  --collector.client.info-labels "ap,band,wlan,name,username,ipv4,ipv6" \
                  --collector.wlan.general \
                  --collector.wlan.traffic \
                  --collector.wlan.config \
                  --collector.wlan.info \
                  --collector.wlan.info-labels "name"'

  exclude_dir = ["assets", "tmp", "vendor", "test_data", ".git", ".github", ".vscode", "node_modules", "dist", "build"]
  exclude_regex = ["_test\\.go"]

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[screen]
  keep_scroll = true
