name: Format and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  fmt:
    uses: umatare5/common/.github/workflows/go-test-fmt.yml@27d895ee9f1410471625dd66c22c0d63bb84b3b7 # v0.13.0
    with:
      go_version: "1.25.1"
      golangci_lint_version: "v2.4.0"
      golangci_lint_config: ".golangci.yml"
